Podfile
re: https://github.com/CocoaPods/CocoaPods/issues/4187
This will turn off [a CocoaPods feature](http://blog.cocoapods.org/CocoaPods-0.38/#deterministic-uuids-by-xcodeproj) which you don't really need that's causing problems for people wanting to compile.
=> [Podfile] Turn off CocoaPods Deterministic UUIDs

ChatSecure/Classes/Controllers/PushController.swift, ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.m, ChatSecure/Classes/Model/Yap Storage/Accounts/OTRXMPPAccount.h, ChatSecure/Classes/Model/Yap Storage/PushContainers.swift, ChatSecure/Classes/OTRAppDelegate.m, ChatSecure/Classes/View Controllers/OTRMessagesViewController.m, ChatSecure/Info.plist, Podfile.lock
There are still some things that could be improved.
Currently on every stream connection it checks for server support of XEP-0357 and re-registers with a new push token. This is probably too aggressive, but it's the least error prone. This push token is not associated with a buddyKey which may cause issues elsewhere, but seems fine so far.
Another issue is that `mod_cloud_notify` is too aggressive when sending push notifications, and will even send them for typing notifications. Since we display "Someone wants to chat" for every received push that doesn't map to a buddy, it can get a little noisy. We can't control the behavior of other XMPP servers so we should address this in the PubSub node and elsewhere in the client.
We will also want to strip as much content as possible in the PubSub …
=> XEP-0357 Support

ChatSecure/Classes/Controllers/Errors.swift, ChatSecure/Classes/Utilities/OTRPasswordGenerator.h, ChatSecure/Classes/Utilities/OTRPasswordGenerator.m, ChatSecure/Classes/Utilities/OTRXMPPError.h, ChatSecure/Classes/Utilities/OTRXMPPError.m, ChatSecure/Classes/View Controllers/Login View Controllers/OTRBaseLoginViewController.m
First it tries to create a JID using the desired nickname. If the
server responds that there is a conflict it appends two random byes in
hex to the end until it is no longer a conflict.
=> Creating an account via nickname ensures JID is unique.

ChatSecure.xcodeproj/project.pbxproj, ChatSecure/Classes/Categories/NSString+ChatSecure.h, ChatSecure/Classes/Categories/NSString+ChatSecure.m, ChatSecure/Classes/Controllers/Errors.swift, ChatSecure/Classes/Utilities/OTRXMPPError.m, ChatSecure/Classes/View Controllers/Login View Controllers/OTRBaseLoginViewController.m, ChatSecureCore/ChatSecureCore.h, ChatSecureTests/OTRStringTests.swift, ChatSecureTests/OTRURLTests.m, ChatSecureTests/PushSerializerTest.swift, OTRAssets/OTRAssets.m
This removes all non english characters using regex, `[^A-Za-z0-9]`. If the jid has no length then we use `[OTRBranding xmppResource]` as the base JID.
As always if a JID conflicts with one on the server then a random string is appended it it. We max out at trying 5 times just to make sure we don't get in an infinite loop.
=> Catch errors where the server does not allow non-english chars in JID

ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
On iPads with split view, the viewWillAppear will not be called, so the DB view was never updated.
=> Fix iPad messages problem

ChatSecure/Classes/View Controllers/Login View Controllers/OTRXLFormCreator.m
In response to Issues #550 and #539, change Validator in jidTextFieldRowDescriptorWithValue to OTRUsernameValidator instead of emailValidator. An alternate solution might be to get rid of the jidTextFieldRowDescriptorWithValue method or just call the usernameTextFieldRowDescriptorWithValue method from the Username field in Add Existing User
=> Allow username with IP address

ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
Seems like there is some kind of race condition, so that if we enter a
chat with a friend that is in "pending approval" state - once this
friend accepts us a session is established but the UI is not correctly
updated (or alternatively a session is never created). This seems to
fix that. Zom issue #313.
=> Move OTR session refresh to end of updateViewWithKey:collection:

ChatSecure/Classes/Controllers/OTRProtocol.h, ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.h, ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.m, ChatSecure/Classes/View Controllers/AccountDetailViewController.swift
Keeping the stream alive when going to background was broken in commit 158bb562d4e32f241674bbb453043be939e08c6b, where `[xmppStream disconnect]` was replaced with `disconnectAfterSending`. These two methods have different semantics: `disconnectAfterSending` sends `</stream>` before closing the socket, and `disconnect` does not.
This solution is not very elegant, but works and does not require changing XMPPFramework.
=> Do not close stream when in background

ChatSecure/Classes/View Controllers/OTRMessagesViewController.h, ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
That way overrides can use images instead of just text.
=> Fix typo and allow deliveryString to be attributed

ChatSecure/Classes/Controllers/XMPP/OTRYapDatabaseRosterStorage.m
This reverts the change that breaks the two-way subscription handling.
Without having looked at it too deeply I think it really strange that this implementation differs logically from those in XMPPUserCoreDataStorageObject.m and XMPPUserMemoryStorageObject.m. Why should they not be the same?
=> Revert to old isPendingApproval implementation

ChatSecure/Classes/Controllers/OTROMEMOSignalCoordinator.swift, ChatSecure/Classes/Controllers/OTROMEMOStorageManager.swift, ChatSecure/Classes/Controllers/XMPP/OTRYapDatabaseRosterStorage.m, ChatSecure/Classes/View Controllers/OTRConversationViewController.m, ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
I think this fixes most of the one-way subscription and OMEMO-not-starting problems.
=> Friending problems

ChatSecure.xcodeproj/project.pbxproj, ChatSecure/Classes/View Controllers/OTRMessagesViewController.m, OTRResources/OTRMessagesLoadingView.xib
The current version does not work very well with large (thousands of messages) histories. The single fact that ChatSecure loads all messages at once affects many areas:
- initial opening;
- loading new messages due to a push notification;
- overall responsiveness (scrolling, typing).
Without going into details, the issue is that too much data is being processed to often without any reason to do so (and often on the UI thread).
There are two main changes in this pull request:
- instead of loading the entire history, load only the last 50 messages, and load the rest on demand;
- handle message loading more efficiently by caching and offloading to background threads the most heavy calculations.
Closes at least #360 & #470, maybe some others.
=> Chatview performance

ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
This message cache thingy "currentMessageIndex" could have caused a looooot of strange issues, since it was never reset in "onReceivedChanges". This meant we could have hit a different object from the one we thought (the currentMessage) in a lot of places!
=> Invalidate stored size info and "one message cache"

ChatSecure/Classes/Controllers/OTRProtocol.h, ChatSecure/Classes/Controllers/OTRProtocolManager.h, ChatSecure/Classes/Controllers/OTRProtocolManager.m, ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.m, ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager_Private.h, ChatSecure/Classes/OTRAppDelegate.m
Disconnect from the background tasks does not always work correctly, because the background task terminates too early. As a result, on the next attempt to connect we're sometimes unable to resume the session.
=> More reliable disconnects

ChatSecure/Classes/Controllers/OTRSplitViewCoordinator.swift
Use the existing shared message view controller when initiating group chat.
=> Don't create new message view controllers

ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoomOccupant.swift
If we have "createIfNeeded" set to true and have jut created a new
object, it is never saved, as the refetch will read back nil again.
=> Don't do a refetch at all

ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
Otherwise, messages could disappear on rotation, to the point of the screen being blank (even on return to the chat view).
=> Reset size cache on rotation change

ChatSecure/Classes/Controllers/FileTransferManager.swift, ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
Also, show clock while waiting for read receipt. Or is there a reason why we didn't do this?
=> Allow retry of failed downloads

ChatSecure/Classes/Controllers/OTRProtocolManager.m, ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.m, ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomManager.m, ChatSecure/Classes/Controllers/XMPP/Storage/RoomStorage.swift, ChatSecure/Classes/Controllers/YapDatabase+ChatSecure.swift, ChatSecure/Classes/Controllers/YapDatabaseTransaction+ChatSecure.swift, ChatSecure/Classes/Model/OTRBuddyCache.h, ChatSecure/Classes/Model/OTRBuddyCache.m, ChatSecure/Classes/Model/Yap Storage/Accounts/OTRXMPPAccount.h, ChatSecure/Classes/Model/Yap Storage/Accounts/OTRXMPPAccount.m, ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoom.swift, ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoomOccupant.swift, ChatSecure/Classes/Model/Yap Storage/SecondaryIndexes.swift, ChatSecure/Classes/OTRAppDelegate.m, ChatSecure/Classes/Utilities/OTRChatDemo.h, ChatSecure/Classes/Utilities/OTRChatDemo.m, ChatSecure/Classes/View Controllers/OTRComposeGroupViewController.swift, ChatSecure/Classes/View Controllers/OTRMessagesCollectionViewFlowLayout.swift, ChatSecure/Classes/View Controllers/OTRMessagesViewController.m, ChatSecure/Classes/View Controllers/OTRRoomOccupantsViewController.swift
I think we have a few things to discuss here, but wanted to get the code up there at least.
=> Occupant deduplication

ChatSecure/Classes/Controllers/ServerCheck.swift, ChatSecure/Classes/Controllers/XMPP/OTRServerCapabilities.m
In about 1 in 10 starts of the app I noticed didNotAuthenticate was
called, because IQ stanza was sent (and the response taken for an auth
response error) before auth was done.
=> Wait for authenticated before start sending IQ stanzas.

ChatSecure/Classes/Controllers/XMPP/Storage/OTRYapDatabaseRosterStorage.m
Haha, we knew we had to be careful about starting to store buddy objects, but already found one issue with this.
=> No longer return true for all buddies in DB

ChatSecure/Classes/Controllers/FileTransferManager.swift
If the file is encrypted, the server might not know its mime type. If that's the case, it will set contenttype to application/octet-stream. If the file is encrypted and this mime type is advertised by the server, we must guess the mime type from the extension
=> Fix displaying of encrypted attachments
