- ChatSecure/Classes/View Controllers/OTRSettingsViewController.m
> Removed XMPPURI scheme replaced with share link

- ChatSecure/Classes/Categories/NSURL+ChatSecure.m
- ChatSecure/Classes/OTRAppDelegate.h
- ChatSecure/Classes/OTRAppDelegate.m
- ChatSecure/Classes/Utilities/OTRTheme.h
- ChatSecure/Classes/Utilities/OTRTheme.m
- ChatSecure/Classes/View Controllers/OTRComposeViewController.h
- ChatSecure/Classes/View Controllers/OTRComposeViewController.m
- ChatSecure/Classes/View Controllers/OTRConversationViewController.m
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.h
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
This one should fix https://github.com/zom/Zom-iOS/issues/5, there was a mismatch between android and iOS flavors of base64 used.
> Use url safe base64 flavor

- ChatSecure/Classes/Model/OTRDomainCellInfo.m
The correct full name is Chaos Computer Club.
> Fix the CCC's name

- ChatSecure/Classes/Controllers/OTRSplitViewCoordinator.swift
- ChatSecure/Classes/View Controllers/OTRNewBuddyViewController.h
- ChatSecure/Classes/View Controllers/OTRNewBuddyViewController.m
Also, use themed conversation vc in coordinator
> Allow newBuddyVC to be created by storyboard

- ChatSecure/Classes/Controllers/XMPP/OTRYapDatabaseRosterStorage.m
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPBuddy.h
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPBuddy.m
- ChatSecure/Classes/OTRAppDelegate.m
- ChatSecure/Classes/View Controllers/OTRConversationViewController.m
> Fixed updating resource status.

- ChatSecure/Classes/Controllers/Errors.swift
- ChatSecure/Classes/Controllers/PushController.swift
- ChatSecure/Classes/Controllers/PushOTRListener.swift
- ChatSecure/Classes/Controllers/PushSerializer.swift
- ChatSecure/Classes/Controllers/PushStorage.swift
- Podfile.lock
This should remove any unused tokens that we have that do not have
their expiration date saved to the database.
This should be tested by @chrisballinger to see if this is really the fix 😄
> Added support for expires_token key

- ChatSecure/Classes/View Controllers/OTRComposeViewController.h
- ChatSecure/Classes/View Controllers/OTRComposeViewController.m
Changed from always using multi select to only enter multi select mode
after tapping group button in navigation bar
> Changed selecting buddies behavior

- ChatSecure/Classes/Utilities/OTRTheme.h
- ChatSecure/Classes/Utilities/OTRTheme.m
- ChatSecure/Classes/View Controllers/Login View Controllers/OTRBaseLoginViewController.m
- ChatSecure/Classes/View Controllers/Onboarding/EnablePushViewController.swift
Add the invite view controller class to the theme, like some of the other view controllers.
> Add the invite view controller class to the theme

- ChatSecure.xcodeproj/project.pbxproj
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.h
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.m
- ChatSecure/Classes/Controllers/XMPP/OTRYapDatabaseRosterStorage.m
- ChatSecure/Classes/Controllers/XMPP/OTRvCardYapDatabaseStorage.m
- ChatSecure/Classes/Model/Yap Storage/Accounts/OTRXMPPAccount.h
- ChatSecure/Classes/Model/Yap Storage/Accounts/OTRXMPPAccount.m
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPBuddy.h
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPBuddy.m
- ChatSecure/Classes/Model/Yap Storage/OTRYapDatabaseObject.h
- ChatSecure/Classes/Model/Yap Storage/OTRYapDatabaseObject.m
- ChatSecure/Classes/Model/Yap Storage/OTRvCard.h
- ChatSecure/Classes/View Controllers/Login View Controllers/OTRXLFormCreator.m
- ChatSecure/Classes/View Controllers/Login View Controllers/OTRXMPPLoginHandler.m
- Podfile.lock
This results in a LOT of noise when connecting/disconnecting, but apparently there's not a good solution.
> Add support for setting & getting vCard nickname

- ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
The limit a bit arbitrarily set to 1Mb.
> Send small audio files from memory

- .gitmodules
Related to comments here https://github.com/ChatSecure/ChatSecure-iOS/pull/683
> Removed YapDatabase submodule

- ChatSecure.xcodeproj/project.pbxproj
- ChatSecureCore/ChatSecureCore.h
Needed for Zom issue 227: https://github.com/zom/Zom-iOS/issues/227
> Export OTRCertificatePinning.h and OTRXMPPServerInfo.h

- ChatSecure/Classes/Controllers/OTRAudioSessionManager.m
- ChatSecure/Classes/Controllers/OTRMediaServer.m
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.h
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
This fixes issues with audio not playing when resuming from background.
> Fix background audio issues

- ChatSecure/Classes/View Controllers/OTRMessagesHoldTalkViewController.m
- ChatSecure/Classes/Views/OTRHoldToTalkView.h
- ChatSecure/Classes/Views/OTRHoldToTalkView.m
... which will happen if the "Permission alert" pops up.
> Abort audio recording if no longer in touch

- ChatSecure/Classes/Controllers/OTREncryptionManager.m
At least set it when the message is delivered, if it is not already set.
> Send date not set on media

- ChatSecure/Classes/Controllers/MessageQueueHandler.swift
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.m
- ChatSecure/Classes/Controllers/YapDatabaseConstants.swift
- ChatSecure/Classes/Model/Yap Storage/YapActions/BuddyActions.swift
- ChatSecure/Classes/View Controllers/OTRComposeViewController.m
Make it a little more generalized to handle "actions" when accounts are connected.
> Change message queue to also handle add/remove buddy

- ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.h
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.m
- ChatSecure/Classes/View Controllers/OTRConversationViewController.m
- ChatSecure/Classes/Views/MigrationInfoHeaderView.swift
@chrisballinger Probably should not be merged to master, but some new feature branch?
This PR adds the "migration info" as a table view header for the chats view and currently pops up the "createNewAccount" view controller from onboarding when "Get Started" is tapped.
> Dukgo migration

- ChatSecure/Classes/View Controllers/OTRConversationViewController.m
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
Fix header layout issues. Also, add logic for checking migration to viewDidAppear instead. And lastly, make sure to save "forwarded buddy" if we created one.
> Dukgo migration fix header

- ChatSecure/Classes/Utilities/OTRTheme.h
- ChatSecure/Classes/Utilities/OTRTheme.m
- ChatSecure/Classes/View Controllers/AccountDetailViewController.swift
- ChatSecure/Classes/View Controllers/OTRSettingsViewController.m
This is needed by Zom to implement the "set as default" account option. Other ways to accomplish this are welcome.
> Allow the account detail view controller to be overridden

- ChatSecure.xcodeproj/project.pbxproj
- ChatSecure/Classes/Controllers/OTRProtocolManager.h
- ChatSecure/Classes/Controllers/OTRProtocolManager.m
- ChatSecure/Classes/Controllers/XMPP/OTRYapDatabaseRosterStorage.m
- ChatSecure/Classes/Model/Yap Storage/Accounts/OTRXMPPAccount+Migration.swift
- ChatSecure/Classes/OTRAppDelegate.m
- ChatSecure/Classes/View Controllers/OTRConversationViewController.m
- ChatSecure/Classes/View Controllers/OTRQRCodeReaderDelegate.m
Reworked this PR and also added code for better handling of invites (with open subscription requests).
> Invite accept requests

- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomManager.m
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomYapStorage.m
Fix crash on receiving group chat message and setup room correctly when creating.
> Group chat fixes

- ChatSecure.xcodeproj/project.pbxproj
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoom.swift
- ChatSecure/Classes/Utilities/OTRGroupAvatarGenerator.swift
- ChatSecure/Classes/View Controllers/OTRRoomOccupantsViewController.swift
Also, open up the room occupants view controller for easier subclassing.
> Group avatars

- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomYapStorage.m
- ChatSecure/Classes/View Controllers/OTRNewBuddyViewController.m
- ChatSecure/Classes/View Controllers/OTRRoomOccupantsViewController.swift
Some member list fixes and strip spaces in otr fingerprint.
> Fix missing url messages

- ChatSecure/Classes/Controllers/OTRMediaFileManager.h
- ChatSecure/Classes/Controllers/OTRMediaFileManager.m
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomManager.m
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomYapStorage.m
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoomOccupant.swift
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
- ChatSecure/Classes/View Controllers/OTRRoomOccupantsViewController.swift
- OTRResources/Interface/OTRRoomOccupants.storyboard
Try to use real buddy avatars and display names in group chats and some other small changes/additions. Should probably be tested more, but posted here as a WIP.
> WIP: Group chat fixes

- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomYapStorage.m
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoomMessage.swift
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoomOccupant.swift
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
- OTRAssets/UIView+OTRAssets.swift
Use new method to get occupant, remove "displayName" from room message object.
> Group name and avatar fix

- ChatSecure.xcodeproj/project.pbxproj
- ChatSecure/Classes/Categories/UITableView+ChatSecure.m
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPManager.h
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomManager.h
- ChatSecure/Classes/Controllers/XMPP/OTRXMPPRoomManager.m
- ChatSecure/Classes/Controllers/XMPP/RoomManager.swift
- ChatSecure/Classes/Controllers/YapDatabaseConstants.swift
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoom.swift
- Podfile
- Podfile.lock
Adds support for automatically bookmarking conferences.
> XEP-0048: Bookmarks

- ChatSecure/Classes/Controllers/FileTransferManager.swift
- ChatSecure/Classes/Controllers/XMPP/Storage/RoomStorage.swift
- ChatSecure/Classes/Model/Yap Storage/OTRXMPPRoomMessage.swift
- ChatSecure/Classes/View Controllers/OTRMessagesViewController.m
- ChatSecure/Classes/View Controllers/OTRRoomOccupantsViewController.swift
Store buddyUniqueId on room messages (if we have it)
> Group fixes

- ChatSecure/Classes/Controllers/XMPP/Storage/MessageStorage.swift
Avoid sending receipts for receipts...
> Small changes to receipt sending logic

- ChatSecure/Classes/Controllers/OTROMEMOSignalCoordinator.swift
I think this is the only place we need it.
> Add receipt request

- README.md
Zom switched from XMPP to Matrix (https://github.com/bascht/omemo-top/pull/181)
> Remove Zom

- ChatSecure/Classes/View Controllers/KeyManagementViewController.swift
> Fix issue where profile fingerprint trust values cannot be updated

- ChatSecureCore/Classes/View Controllers/Login View Controllers/OTRBaseLoginViewController.m
- ChatSecureCore/Classes/View Controllers/Login View Controllers/OTRXLFormCreator.m
- ChatSecureCore/Classes/View Controllers/Login View Controllers/OTRXMPPCreateAccountHandler.m
- ChatSecureCore/Classes/View Controllers/Login View Controllers/OTRXMPPLoginHandler.m
- ChatSecureCore/Public/OTRXLFormCreator.h
- OTRResources/Interface/Onboarding.storyboard
- OTRResources/Interface/XMPPServerInfoCell.xib
This is a first pass at removing the new signup server list. Unfortunately none of the servers in the [current list](https://github.com/ChatSecure/xmpp-server-list) work for new signups. Some of this is likely related to missing CAPTCHA support, or simply that the servers are no longer operating.
> Remove outdated server list for new signups
